ArtClub/Controllers/AddMembersController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using ArtClub.Models;
using System.Net;

namespace ArtClub.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AddMembersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public AddMembersController()
        {
        }

        public AddMembersController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        //
        // GET: /Account/Register
        [Authorize(Roles = "Admin")]
        public ActionResult Register()
        {
            return View();
        }

        //
        // POST: /Account/Register
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.Email, Email = model.Email };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);

                    // For more information on how to enable account confirmation and password reset please visit https://go.microsoft.com/fwlink/?LinkID=320771
                    // Send an email with this link
                    // string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    // var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    // await UserManager.SendEmailAsync(user.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");

                    return RedirectToAction("Index");
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewRequests()
        {
            return View(db.UserRequestsModels.ToList());
        }

        // GET: Events/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserRequestsModels userRequestsModels = db.UserRequestsModels.Find(id);
            if (userRequestsModels == null)
            {
                return HttpNotFound();
            }
            return View(userRequestsModels);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserRequestsModels userRequestsModels = db.UserRequestsModels.Find(id);
            db.UserRequestsModels.Remove(userRequestsModels);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ArtClub/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ART Club", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @Html.Partial("_LogedTabs")
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="row">
                <div class="col-md-6">
                    <p>&copy; @DateTime.Now.Year - Art-Club All Rights Reserved.</p>
                </div>
                <div class="col-md-6">
                    <p>
                        <div style='text-align: right;'>

                            <a href='https://www.linkedin.com' target='_blank' title='Visit Us On Linkedin'>
                                <img src="/Images/linkedin.png" style='border: 0px;' alt='Visit Us On Linkedin' height='40px' width='40px' />
                            </a>
                            <a href='https://twitter.com/twitter' target='_blank' title='Visit Us On Twitter'>
                                <img src="/Images/twitter.png" style='border: 0px;' alt='Visit Us On Twitter' height='40px' width='40px' />
                            </a>
                            <a href='https://www.facebook.com/' target='_blank' title='Visit Us On Facebook'>
                                <img src="/Images/facebook.png" style='border: 0px;' alt='Visit Us On Facebook' height='40px' width='40px' />
                            </a>
                            <a href='https://plus.google.com/' target='_blank' title='Visit Us On Google Plus'>
                                <img src="/Images/googleplus.png" style='border: 0px;' alt='Visit Us On Google Plus' height='40px' width='40px' />
                            </a>
                        </div>
                    </p>
                </div>
            </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ArtClub/Views/Shared/_LogedTabs.cshtml
@using Microsoft.AspNet.Identity

@if (Request.IsAuthenticated)
{
    <li>@Html.ActionLink("Events", "Index", "Events")</li>

    if (Context.User.IsInRole("Admin"))
    {
        <li>@Html.ActionLink("Reservations", "Index", "Reservations")</li>
        <li>@Html.ActionLink("Payments", "Index", "Payments")</li>
        <li>@Html.ActionLink("Locations", "Index", "Locations")</li>
        <li>@Html.ActionLink("Add Member", "Index", "AddMembers")</li>
        <li>@Html.ActionLink("Reports", "Index", "Reports")</li>
    }
    else
    {
        <li>@Html.ActionLink("Locations", "Index", "LocationsPreview")</li>
        <li>@Html.ActionLink("My Initations", "Index", "EventGuests")</li>
    }
}
else
{
    <li>@Html.ActionLink("Book Location", "BookLocation", "Home")</li>
}